apiVersion: v1
kind: Service
metadata:
  name: {{ template "hdfs.fullname" . }}-openresty
  labels:
    app: {{ template "hdfs.fullname" . }}-openresty
    component: proxy
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9870
    targetPort: 9870
    protocol: TCP
  selector:
    app: {{ template "hdfs.fullname" . }}-openresty

