apiVersion: v1
kind: Service
metadata:
  name: {{ template "hdfs.fullname" . }}-journalnodes
  labels:
    {{ include "hdfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: journalnode
spec:
  type: ClusterIP
  selector:
    {{- include "hdfs.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: journalnode
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.journalnode.ports.http }}
    targetPort: http